language: java
jdk:
- oraclejdk11

services:
- rabbitmq
- mongodb

notifications:
  slack: gridgo:EkUUzu8RhdhIVeNKg9JlcuIv

before_install:
  - sudo apt-get install -y libpgm-dev

after_success:
- mvn clean test jacoco:report coveralls:report -DrepoToken=$CoverallsRepoToken
