language: java
jdk:
- oraclejdk11

services:
- rabbitmq
- mongodb
- redis-server
- mysql

notifications:
  slack: gridgo:EkUUzu8RhdhIVeNKg9JlcuIv
  
addons:
  sonarcloud:
    organization: "gridgo"
    token: $SONAR_TOKEN

before_install:
  - sudo apt-get install -y libpgm-dev 
  - sudo apt-get install -y libstdc++6
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'


after_success:
- mvn clean test jacoco:report sonar:sonar -Dsonar.projectKey=gridgo_gridgo-connector coveralls:report -DrepoToken=$CoverallsRepoToken
