language: java
jdk:
- oraclejdk11

services:
- rabbitmq

notifications:
  slack: gridgo:EkUUzu8RhdhIVeNKg9JlcuIv

after_success:
- mvn clean test jacoco:report coveralls:report -DrepoToken=$CoverallsRepoToken
