/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_ZMQ_Poller */

#ifndef _Included_org_zeromq_ZMQ_Poller
#define _Included_org_zeromq_ZMQ_Poller
#ifdef __cplusplus
extern "C" {
#endif
#undef org_zeromq_ZMQ_Poller_POLLIN
#define org_zeromq_ZMQ_Poller_POLLIN 1L
#undef org_zeromq_ZMQ_Poller_POLLOUT
#define org_zeromq_ZMQ_Poller_POLLOUT 2L
#undef org_zeromq_ZMQ_Poller_POLLERR
#define org_zeromq_ZMQ_Poller_POLLERR 4L
#undef org_zeromq_ZMQ_Poller_SIZE_DEFAULT
#define org_zeromq_ZMQ_Poller_SIZE_DEFAULT 32L
#undef org_zeromq_ZMQ_Poller_SIZE_INCREMENT
#define org_zeromq_ZMQ_Poller_SIZE_INCREMENT 16L
/*
 * Class:     org_zeromq_ZMQ_Poller
 * Method:    run_poll
 * Signature: ([Lorg/zeromq/ZMQ/PollItem;IJ)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_ZMQ_00024Poller_run_1poll
  (JNIEnv *, jclass, jobjectArray, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
