/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_ZMQ_Curve_KeyPair */

#ifndef _Included_org_zeromq_ZMQ_Curve_KeyPair
#define _Included_org_zeromq_ZMQ_Curve_KeyPair
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
