/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_ZMQ_Curve */

#ifndef _Included_org_zeromq_ZMQ_Curve
#define _Included_org_zeromq_ZMQ_Curve
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_ZMQ_Curve
 * Method:    generateKeyPair
 * Signature: ()Lorg/zeromq/ZMQ/Curve/KeyPair;
 */
JNIEXPORT jobject JNICALL Java_org_zeromq_ZMQ_00024Curve_generateKeyPair
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_ZMQ_Curve
 * Method:    z85Decode
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_zeromq_ZMQ_00024Curve_z85Decode
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_ZMQ_Curve
 * Method:    z85Encode
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_ZMQ_00024Curve_z85Encode
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
