/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_ZMQ_Event */

#ifndef _Included_org_zeromq_ZMQ_Event
#define _Included_org_zeromq_ZMQ_Event
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_ZMQ_Event
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zeromq_ZMQ_00024Event_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_ZMQ_Event
 * Method:    recv
 * Signature: (JI)Lorg/zeromq/ZMQ/Event;
 */
JNIEXPORT jobject JNICALL Java_org_zeromq_ZMQ_00024Event_recv
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
